substitutions:
  device_id: front_entry_lights_2
  device_name: Front Entry Lights 2
  ip_address: !secret front_entry_lights_2_ip
  ota_pwd: !secret front_entry_lights_2_ota_pwd
  api_pwd: !secret front_entry_lights_2_api_pwd
  ap_wifi_pwd: !secret front_entry_lights_2_ap_wifi_pwd
  day_brightness: "1"
  night_brightness: ".03"
  day_auto_off_minutes: "0"
  night_auto_off_minutes: "15"
  linked_lights: ""
  double_tap_while_off_stays_on: "true"

script:
  - id: startup
    then:
      - lambda: |-

packages:
  feit_dimmer: !include ../packages/feit_dimmer.yaml
