substitutions:
  device_id: living_room_lights
  device_name: Living Room Lights
  ip_address: !secret living_room_lights_ip
  ota_pwd: !secret living_room_lights_ota_pwd
  api_pwd: !secret living_room_lights_api_pwd
  ap_wifi_pwd: !secret living_room_lights_ap_wifi_pwd
  day_brightness: "1"
  night_brightness: ".03"
  day_auto_off_minutes: "0"
  night_auto_off_minutes: "15"
  linked_lights: ""
  double_tap_while_off_stays_on: "true"

script:
  - id: startup
    then:
      - lambda: |-

packages:
  feit_dimmer: !include ../packages/feit_dimmer.yaml
